name: Build and deploy

on:
  push:

jobs:
  build_samples:
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v5
      - name: Generate sample
        run: |
          cd backend
          node script/generate_couchdb_data.js
      - name: Save samples for later
        uses: actions/upload-artifact@v4
        with:
          name: samples
          path: sample_data.json



  measure_ecoindex:
    needs:
      - build_samples
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v5
      - name: Start application
        uses: ./.github/actions/start
      - name: Install GreenIT Analysis CLI
        run: |
          wget https://github.com/cnumr/GreenIT-Analysis-cli/archive/refs/heads/master.zip
          unzip master.zip
          cd GreenIT-Analysis-cli-master
          npm install
          npm link
      - name: Run GreenIT Analysis CLI
        run: |
          greenit analyse --format html --ci scenarios/read_daily_articles.yml
      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: EcoIndex
          path: Consulterlesactualites.html

  measure_energy_consumption:
    needs:
      - build_samples
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v5
      - name: Start application
        uses: ./.github/actions/start
      - name: Install GreenFrame CLI
        run: |
          wget https://github.com/benel/greenframe-cli/archive/refs/heads/post-app.zip
          unzip post-app.zip
          cd greenframe-cli-post-app
          npm install -g corepack
          yarn
          yarn build 
      - name: Run GreenIT Analysis CLI for multiple scenarios
        run: |
          for scenario in scenarios/*.yml; do
            echo "Analyse de $scenario"
            greenit analyse --format html --ci "$scenario"
          done
      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: EcoIndex
          path: "*.html"